export const translations = {
  en: {
    findId: "Find ID",
    documents: "Documents",
    roadmap: "Roadmap",
    searchIds: "Search IDs",
    alreadyHave: "Already Have This",
    emptyRoadmap: "Select a document from 'Find ID' to generate a route.",
    explorer: "Explorer",
    history: "History",
    settings: "Settings",
    darkMode: "Dark Mode",
    dbVersion: "Database Version: v2.1 (114 Branches Verified)",
    clearChecklist: "Clear Saved Checklists",
    clearChecklistSuccess: "Possessed checklist cleared successfully!",
    clearChecklistConfirm: "Are you sure you want to clear your saved documents? This cannot be undone.",
    yes: "Yes",
    cancel: "Cancel",
    fee: "Fee",
    processTime: "Process Time",
    markAsDone: "Mark as Done",
    
    // Checklist Screen
    checklistSubtitleSimple: "Check the documents you already have:",
    checklistSubtitleAdvanced: "Check off the documents you already possess to personalize your roadmaps.",
    searchPlaceholder: "Search documents...",
    findDocumentSimple: "Find a Document",
    
    // Target Screen
    targetTitle: "What do you need?",
    targetSubtitle: "Select the document you want to obtain.",
    targetInfo: "Documents you already have are greyed out and cannot be selected as a target.",
    
    // Roadmap Screen
    journeyToGetSimple: "YOUR JOURNEY TO GET",
    activeRoadmapAdvanced: "ACTIVE ROADMAP",
    remainingSteps: "Remaining",
    fullPath: "Full Path",
    totalNodes: "Total Nodes",
    edges: "Edges",
    owned: "Owned",
    remaining: "Remaining",
    estDays: "Est. Days",
    estCost: "Est. Cost",
    step: "step",
    steps: "steps",
    getDirections: "Get Directions",
    nearestBranch: "Nearest Branch",
    noActiveJourney: "Select a document you want to get in the 'Find ID' tab to start.",
    allStepsDone: "All steps complete! Check your History tab.",
    
    // Explorer Screen
    explorerSubtitleAdvanced: "Interactive dependency visualization",
    explorerTitleSimple: "Guide",
    explorerSubtitleSimple: "Step-by-step help guide",
    colorLegendOwned: "Owned",
    colorLegendAvailable: "Available",
    colorLegendLocked: "Locked",
    colorLegendTarget: "Target",
    noActiveJourneyGuide: "Go to the Find ID tab and choose a document you want to get. We will lay out a simple timeline here to guide you!",
    chooseTargetIdBtn: "Choose a Target ID",
    noActiveJourneyGuideTitle: "No Active Journey Yet",
    faqSectionTitle: "Frequently Asked Questions",
    
    // History Screen
    historySubtitle: "A log of all document acquisition roadmaps you have successfully completed.",
    historyEmptyState: "No completed flows yet.",
    historyEmptyStateSubtitle: "Complete all steps in a roadmap to see it recorded here.",
    completedOn: "Completed on",
    completed: "completed",
    
    // Linear Timeline
    documentJourneyMap: "Document Journey Map",
    nextStep: "NEXT STEP",

    // Algorithm Trace
    algorithmTraceTitle: "Kahn's Algorithm Trace",
    algorithmTraceSub: "Educational DAA Walkthrough",
    stepWord: "Step",
    ofWord: "of",
    dequeuedNode: "DEQUEUED NODE (IN-DEGREE 0)",
    queueBefore: "QUEUE BEFORE DEQUEUE",
    queueAfter: "QUEUE AFTER DEQUEUE & DEC",
    neighborDecrements: "NEIGHBOR IN-DEGREE DECREMENTS",
    traceSelectActive: "Select an active target document to see Kahn's Algorithm trace.",
    noOutwardDeps: "No outward dependency neighbors. No in-degree decrements.",
    reset: "Reset",
    running: "RUNNING",
    enqueued: "ENQUEUED",
    emptyBrackets: "[ Empty ]",
    
    // Node Detail Sheet
    possessed: "Possessed",
    activeTarget: "Active Target",
    estFees: "Est. Fees",
    issuingOffice: "Issuing Office",
    prereqsHeader: "Prerequisites",
    noPrereqs: "None — This is a foundational document.",
    unlocksHeader: "Unlocks",
    noUnlocks: "None — This document does not lead to further requirements.",
    setAsTarget: "Set as Target",
    markAsMissing: "Mark as Missing",
    markAsPossessed: "Mark as Possessed",
  },
  tl: {
    findId: "Maghanap ng ID",
    documents: "Dokumento",
    roadmap: "Giya sa Ruta",
    searchIds: "Maghanap ng ID",
    alreadyHave: "Taglay mo na ito",
    emptyRoadmap: "Pumili ng dokumento sa 'Maghanap ng ID' para gumawa ng ruta.",
    explorer: "Giya",
    history: "Kasaysayan",
    settings: "Mga Setting",
    darkMode: "Dark Mode",
    dbVersion: "Bersyon ng Database: v2.1 (114 Branches Verified)",
    clearChecklist: "Burahin ang Naka-save na Checklist",
    clearChecklistSuccess: "Matagumpay na nabura ang mga naka-save na dokumento!",
    clearChecklistConfirm: "Sigurado ka bang gusto mong burahin ang mga naka-save na dokumento? Hindi ito mababawi.",
    yes: "Oo",
    cancel: "Kanselahin",
    fee: "Bayad",
    processTime: "Tagal ng Proseso",
    markAsDone: "Markahan na Tapos",
    
    // Checklist Screen
    checklistSubtitleSimple: "Markahan ang mga dokumentong mayroon ka na:",
    checklistSubtitleAdvanced: "Markahan ang mga dokumentong taglay mo na para i-personalize ang iyong mga roadmap.",
    searchPlaceholder: "Maghanap ng dokumento...",
    findDocumentSimple: "Maghanap ng Dokumento",
    
    // Target Screen
    targetTitle: "Ano ang kailangan mo?",
    targetSubtitle: "Piliin ang dokumentong nais mong makuha.",
    targetInfo: "Ang mga dokumentong mayroon ka na ay kulay-abo at hindi maaaring piliin.",
    
    // Roadmap Screen
    journeyToGetSimple: "ANG IYONG GABAY PARA MAKUHA ANG",
    activeRoadmapAdvanced: "AKTIBONG RUTA",
    remainingSteps: "Natitira",
    fullPath: "Buong Ruta",
    totalNodes: "Kabuuang Nodes",
    edges: "Edges",
    owned: "Mayroon",
    remaining: "Natitira",
    estDays: "Tinatayang Araw",
    estCost: "Tinatayang Gastos",
    step: "hakbang",
    steps: "hakbang",
    getDirections: "Kumuha ng Direksyon",
    nearestBranch: "Pinakamalapit na Sangay",
    noActiveJourney: "Pumili ng dokumentong nais mong makuha sa 'Maghanap ng ID' tab para magsimula.",
    allStepsDone: "Kumpleto na ang lahat ng hakbang! Tingnan ang iyong Kasaysayan tab.",
    
    // Explorer Screen
    explorerSubtitleAdvanced: "Interaktibong visualization ng dependency",
    explorerTitleSimple: "Gabay",
    explorerSubtitleSimple: "Hakbang-hakbang na gabay sa tulong",
    colorLegendOwned: "Taglay Na",
    colorLegendAvailable: "Maaaring Makuha",
    colorLegendLocked: "Naka-lock",
    colorLegendTarget: "Target",
    noActiveJourneyGuide: "Pumunta sa Maghanap ng ID tab at pumili ng dokumentong nais mong makuha. Maglalagay kami ng simpleng timeline dito para gabayan ka!",
    chooseTargetIdBtn: "Pumili ng Target na ID",
    noActiveJourneyGuideTitle: "Wala Pang Aktibong Gabay",
    faqSectionTitle: "Mga Madalas Itanong",
    
    // History Screen
    historySubtitle: "Isang talaan ng lahat ng nakumpletong roadmap sa pagkuha ng dokumento.",
    historyEmptyState: "Wala pang nakumpletong mga ruta.",
    historyEmptyStateSubtitle: "Kumpletuhin ang lahat ng hakbang sa isang roadmap upang makita ito dito.",
    completedOn: "Natapos noong",
    completed: "ang natapos",
    
    // Linear Timeline
    documentJourneyMap: "Mapa ng Paglalakbay ng Dokumento",
    nextStep: "SUSUNOD NA HAKBANG",

    // Algorithm Trace
    algorithmTraceTitle: "Trace ng Kahn's Algorithm",
    algorithmTraceSub: "Edukasyonal na DAA Walkthrough",
    stepWord: "Hakbang",
    ofWord: "ng",
    dequeuedNode: "DEQUEUED NODE (IN-DEGREE 0)",
    queueBefore: "QUEUE BAGO I-DEQUEUE",
    queueAfter: "QUEUE MATAPOS I-DEQUEUE at I-DEC",
    neighborDecrements: "PAGBABAWAS NG IN-DEGREE NG KAPITBAHAY",
    traceSelectActive: "Pumili ng aktibong target na dokumento para makita ang trace ng Kahn's Algorithm.",
    noOutwardDeps: "Walang palabas na dependency na kapitbahay. Walang pagbabawas ng in-degree.",
    reset: "I-reset",
    running: "TUMATAKBO",
    enqueued: "NAISAMA SA QUEUE",
    emptyBrackets: "[ Walang Laman ]",
    
    // Node Detail Sheet
    possessed: "Taglay Na",
    activeTarget: "Aktibong Target",
    estFees: "Tinatayang Bayad",
    issuingOffice: "Naglalabas na Opisina",
    prereqsHeader: "Mga Prerequisite",
    noPrereqs: "Wala — Ito ay isang foundational document.",
    unlocksHeader: "Nagbubukas",
    noUnlocks: "Wala — Ang dokumentong ito ay hindi humahantong sa iba pang mga requirement.",
    setAsTarget: "Itakda bilang Target",
    markAsMissing: "Markahan bilang Nawawala",
    markAsPossessed: "Markahan bilang Taglay",
  }
} as const;
